script_engine_names:
  - js
  - JS
  - javascript
  - JavaScript
  - ecmascript
  - ECMAScript
  - nashorn
  - Nashorn

# if this option is true, even if ScriptEngineManager already has a factory
# for JavaScript, this plugin will try to replace it with openjdk nashorn.
ForceNashorn: false
